Add container logic
indiainvestments/nitrate pull request #2
Opened 2021-09-26 16:24 UTC by alayek

Add container logic to test max width of the header and content

2021-09-27 03:50 UTC, crimelabs786 commented
@alayek please mark this as a draft PR or WIP if it's not ready to merge yet.

2021-09-27 14:44 UTC, alayek commented
Closes #6

2021-09-27 18:45 UTC, financenoob commented
Bit of a nitpick. You should extract long class names into variables or functions if they are to be changed using state.

2021-09-27 18:48 UTC, financenoob commented
Next time, please scope your PR to a single concern or issue.

2021-09-29 13:48 UTC, financenoob requested changes

2021-09-29 13:55 UTC, financenoob commented
> @financenoob have addressed your concerns, and moved the class logic to `useMemo`. Do you feel using memo is an overkill here?

It does seem overkill here. I would err on removing it.

2021-09-30 05:08 UTC, alayek commented on hooks/use-dark-mode/use-dark-mode.tsx
> +  const { theme, setTheme } = useTheme();
Fixed, thanks for pointing out.

2021-09-30 10:05 UTC, crimelabs786 commented
Let's merge it for now, we can address pending stuff in future PRs.

2021-09-30 10:05 UTC, crimelabs786 approved these changes

2021-09-30 10:53 UTC, financenoob approved these changes

2021-09-30 11:01 UTC, merged